version: '3'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app/src:/var/www/html/
        ports:
          - 8000:80
#          - 80
#        labels:
#          - "traefik.enable=true"
#          - "trafik.http.routers.php-apache.rule=Host:hashtagoo.cf"
#          - "traefik.port=80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - '8001:80'
      restart: always
      environment:
        PMA_HOST: db
      depends_on:
        - db
